// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NcsScheduler.Data;

#nullable disable

namespace NcsScheduler.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260301010214_AddNetSeasonDates")]
    partial class AddNetSeasonDates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NcsScheduler.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NetControllerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NetControllerId")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("NcsScheduler.Models.Domain.BandCoordinator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NetControllerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NetControllerId")
                        .IsUnique();

                    b.ToTable("BandCoordinators");
                });

            modelBuilder.Entity("NcsScheduler.Models.Domain.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvitedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NetControllerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NetControllerId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("NcsScheduler.Models.Domain.Net", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Band")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FrequencyMhz")
                        .HasColumnType("TEXT");

                    b.Property<string>("FrequencyRange")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("ScheduledTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("SeasonEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("SeasonStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Nets");
                });

            modelBuilder.Entity("NcsScheduler.Models.Domain.NetController", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MemberNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotifyOnAssigned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyOnSlotOpened")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Callsign")
                        .IsUnique();

                    b.ToTable("NetControllers");
                });

            modelBuilder.Entity("NcsScheduler.Models.Domain.NetControllerPool", b =>
                {
                    b.Property<int>("NetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NetControllerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("NetId", "NetControllerId");

                    b.HasIndex("NetControllerId");

                    b.ToTable("NetControllerPool");
                });

            modelBuilder.Entity("NcsScheduler.Models.Domain.NetCoordinatorAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BandCoordinatorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("NetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BandCoordinatorId");

                    b.HasIndex("NetId");

                    b.ToTable("NetCoordinatorAssignments");
                });

            modelBuilder.Entity("NcsScheduler.Models.Domain.NetScheduleRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NetId");

                    b.ToTable("NetScheduleRules");
                });

            modelBuilder.Entity("NcsScheduler.Models.Domain.NetSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HolidayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("NetId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("ScheduledTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NetId", "SessionDate")
                        .IsUnique();

                    b.ToTable("NetSessions");
                });

            modelBuilder.Entity("NcsScheduler.Models.Domain.SessionAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignmentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NetControllerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NetSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NetControllerId");

                    b.HasIndex("NetSessionId");

                    b.ToTable("SessionAssignments");
                });

            modelBuilder.Entity("NcsScheduler.Models.Domain.StandingAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("TEXT");

                    b.Property<int>("NetControllerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NetControllerId");

                    b.HasIndex("NetId");

                    b.ToTable("StandingAssignments");
                });

            modelBuilder.Entity("NcsScheduler.Models.Domain.Unavailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MarkedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarkedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NetControllerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NetControllerId");

                    b.HasIndex("NetId");

                    b.ToTable("Unavailabilities");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NcsScheduler.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NcsScheduler.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NcsScheduler.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NcsScheduler.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NcsScheduler.Data.ApplicationUser", b =>
                {
                    b.HasOne("NcsScheduler.Models.Domain.NetController", "NetController")
                        .WithOne()
                        .HasForeignKey("NcsScheduler.Data.ApplicationUser", "NetControllerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NetController");
                });

            modelBuilder.Entity("NcsScheduler.Models.Domain.BandCoordinator", b =>
                {
                    b.HasOne("NcsScheduler.Models.Domain.NetController", "NetController")
                        .WithOne("BandCoordinator")
                        .HasForeignKey("NcsScheduler.Models.Domain.BandCoordinator", "NetControllerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NetController");
                });

            modelBuilder.Entity("NcsScheduler.Models.Domain.Invitation", b =>
                {
                    b.HasOne("NcsScheduler.Models.Domain.NetController", "NetController")
                        .WithMany()
                        .HasForeignKey("NetControllerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NetController");
                });

            modelBuilder.Entity("NcsScheduler.Models.Domain.NetControllerPool", b =>
                {
                    b.HasOne("NcsScheduler.Models.Domain.NetController", "NetController")
                        .WithMany("PoolMemberships")
                        .HasForeignKey("NetControllerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NcsScheduler.Models.Domain.Net", "Net")
                        .WithMany("ControllerPool")
                        .HasForeignKey("NetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Net");

                    b.Navigation("NetController");
                });

            modelBuilder.Entity("NcsScheduler.Models.Domain.NetCoordinatorAssignment", b =>
                {
                    b.HasOne("NcsScheduler.Models.Domain.BandCoordinator", "BandCoordinator")
                        .WithMany("NetAssignments")
                        .HasForeignKey("BandCoordinatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NcsScheduler.Models.Domain.Net", "Net")
                        .WithMany("CoordinatorAssignments")
                        .HasForeignKey("NetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BandCoordinator");

                    b.Navigation("Net");
                });

            modelBuilder.Entity("NcsScheduler.Models.Domain.NetScheduleRule", b =>
                {
                    b.HasOne("NcsScheduler.Models.Domain.Net", "Net")
                        .WithMany("ScheduleRules")
                        .HasForeignKey("NetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Net");
                });

            modelBuilder.Entity("NcsScheduler.Models.Domain.NetSession", b =>
                {
                    b.HasOne("NcsScheduler.Models.Domain.Net", "Net")
                        .WithMany("Sessions")
                        .HasForeignKey("NetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Net");
                });

            modelBuilder.Entity("NcsScheduler.Models.Domain.SessionAssignment", b =>
                {
                    b.HasOne("NcsScheduler.Models.Domain.NetController", "NetController")
                        .WithMany("SessionAssignments")
                        .HasForeignKey("NetControllerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NcsScheduler.Models.Domain.NetSession", "NetSession")
                        .WithMany("Assignments")
                        .HasForeignKey("NetSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NetController");

                    b.Navigation("NetSession");
                });

            modelBuilder.Entity("NcsScheduler.Models.Domain.StandingAssignment", b =>
                {
                    b.HasOne("NcsScheduler.Models.Domain.NetController", "NetController")
                        .WithMany("StandingAssignments")
                        .HasForeignKey("NetControllerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NcsScheduler.Models.Domain.Net", "Net")
                        .WithMany("StandingAssignments")
                        .HasForeignKey("NetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Net");

                    b.Navigation("NetController");
                });

            modelBuilder.Entity("NcsScheduler.Models.Domain.Unavailability", b =>
                {
                    b.HasOne("NcsScheduler.Models.Domain.NetController", "NetController")
                        .WithMany("Unavailabilities")
                        .HasForeignKey("NetControllerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NcsScheduler.Models.Domain.Net", "Net")
                        .WithMany()
                        .HasForeignKey("NetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Net");

                    b.Navigation("NetController");
                });

            modelBuilder.Entity("NcsScheduler.Models.Domain.BandCoordinator", b =>
                {
                    b.Navigation("NetAssignments");
                });

            modelBuilder.Entity("NcsScheduler.Models.Domain.Net", b =>
                {
                    b.Navigation("ControllerPool");

                    b.Navigation("CoordinatorAssignments");

                    b.Navigation("ScheduleRules");

                    b.Navigation("Sessions");

                    b.Navigation("StandingAssignments");
                });

            modelBuilder.Entity("NcsScheduler.Models.Domain.NetController", b =>
                {
                    b.Navigation("BandCoordinator");

                    b.Navigation("PoolMemberships");

                    b.Navigation("SessionAssignments");

                    b.Navigation("StandingAssignments");

                    b.Navigation("Unavailabilities");
                });

            modelBuilder.Entity("NcsScheduler.Models.Domain.NetSession", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
