namespace NcsScheduler.Models.Domain;

public class Holiday
{
    public int Id { get; set; }
    public DateOnly Date { get; set; }
    public string Name { get; set; } = "";
    public int Year { get; set; }
    public bool IsAutoGenerated { get; set; }
}
