using Microsoft.EntityFrameworkCore;
using NcsScheduler.Data;
using NcsScheduler.Models.Domain;

namespace NcsScheduler.Services;

public interface IHolidayService
{
    List<Holiday> CalculateHolidaysForYear(int year);
    Task<List<Holiday>> GenerateHolidaysForYearAsync(int year);
}

public class HolidayService : IHolidayService
{
    private readonly ApplicationDbContext _db;

    public HolidayService(ApplicationDbContext db) => _db = db;

    public List<Holiday> CalculateHolidaysForYear(int year)
    {
        var holidays = new List<Holiday>();

        void Add(DateOnly date, string name, bool applyObserved = false)
        {
            if (applyObserved)
                date = ApplyObservedRule(date);
            holidays.Add(new Holiday
            {
                Date = date,
                Name = name,
                Year = year,
                IsAutoGenerated = true
            });
        }

        // New Year's Day — Jan 1 (observed)
        Add(new DateOnly(year, 1, 1), "New Year's Day", applyObserved: true);

        // Martin Luther King Jr. Day — 3rd Monday of January
        Add(NthDayOfWeekInMonth(year, 1, DayOfWeek.Monday, 3), "Martin Luther King Jr. Day");

        // Presidents' Day (Washington's Birthday) — 3rd Monday of February
        Add(NthDayOfWeekInMonth(year, 2, DayOfWeek.Monday, 3), "Presidents' Day");

        // Memorial Day — Last Monday of May
        Add(LastDayOfWeekInMonth(year, 5, DayOfWeek.Monday), "Memorial Day");

        // Juneteenth — June 19 (observed)
        Add(new DateOnly(year, 6, 19), "Juneteenth", applyObserved: true);

        // Independence Day — July 4 (observed)
        Add(new DateOnly(year, 7, 4), "Independence Day", applyObserved: true);

        // Labor Day — 1st Monday of September
        Add(NthDayOfWeekInMonth(year, 9, DayOfWeek.Monday, 1), "Labor Day");

        // Columbus Day — 2nd Monday of October
        Add(NthDayOfWeekInMonth(year, 10, DayOfWeek.Monday, 2), "Columbus Day");

        // Veterans Day — November 11 (observed)
        Add(new DateOnly(year, 11, 11), "Veterans Day", applyObserved: true);

        // Thanksgiving — 4th Thursday of November
        Add(NthDayOfWeekInMonth(year, 11, DayOfWeek.Thursday, 4), "Thanksgiving Day");

        // Christmas Day — December 25 (observed)
        Add(new DateOnly(year, 12, 25), "Christmas Day", applyObserved: true);

        return holidays.OrderBy(h => h.Date).ToList();
    }

    public async Task<List<Holiday>> GenerateHolidaysForYearAsync(int year)
    {
        var calculated = CalculateHolidaysForYear(year);

        var existing = await _db.Holidays
            .Where(h => h.Year == year)
            .ToListAsync();

        var existingKeys = existing
            .Select(h => (h.Date, h.Name))
            .ToHashSet();

        foreach (var h in calculated)
        {
            if (!existingKeys.Contains((h.Date, h.Name)))
                _db.Holidays.Add(h);
        }

        await _db.SaveChangesAsync();

        return await _db.Holidays
            .Where(h => h.Year == year)
            .OrderBy(h => h.Date)
            .ToListAsync();
    }

    /// <summary>
    /// Federal observed rule: Saturday → Friday, Sunday → Monday.
    /// </summary>
    private static DateOnly ApplyObservedRule(DateOnly date) => date.DayOfWeek switch
    {
        DayOfWeek.Saturday => date.AddDays(-1),
        DayOfWeek.Sunday => date.AddDays(1),
        _ => date
    };

    /// <summary>
    /// Returns the nth occurrence of a day-of-week in a given month.
    /// e.g. NthDayOfWeekInMonth(2026, 1, Monday, 3) → 3rd Monday of Jan 2026.
    /// </summary>
    private static DateOnly NthDayOfWeekInMonth(int year, int month, DayOfWeek dow, int n)
    {
        var first = new DateOnly(year, month, 1);
        int daysUntil = ((int)dow - (int)first.DayOfWeek + 7) % 7;
        return first.AddDays(daysUntil + (n - 1) * 7);
    }

    /// <summary>
    /// Returns the last occurrence of a day-of-week in a given month.
    /// e.g. LastDayOfWeekInMonth(2026, 5, Monday) → last Monday of May 2026.
    /// </summary>
    private static DateOnly LastDayOfWeekInMonth(int year, int month, DayOfWeek dow)
    {
        var last = new DateOnly(year, month, DateTime.DaysInMonth(year, month));
        int daysSince = ((int)last.DayOfWeek - (int)dow + 7) % 7;
        return last.AddDays(-daysSince);
    }
}
