using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NcsScheduler.Data;
using NcsScheduler.Models.Domain;
using NcsScheduler.Models.ViewModels;
using NcsScheduler.Services;

namespace NcsScheduler.Controllers;

[Authorize(Policy = "CanManageNets")]
public class HolidaysController : Controller
{
    private readonly ApplicationDbContext _db;
    private readonly IHolidayService _holidayService;

    public HolidaysController(ApplicationDbContext db, IHolidayService holidayService)
    {
        _db = db;
        _holidayService = holidayService;
    }

    public async Task<IActionResult> Index(int? year)
    {
        var currentYear = DateTime.UtcNow.Year;
        var selectedYear = year ?? currentYear;

        var holidays = await _db.Holidays
            .Where(h => h.Year == selectedYear)
            .OrderBy(h => h.Date)
            .ToListAsync();

        // Build list of available years (distinct years in DB + current + next)
        var dbYears = await _db.Holidays
            .Select(h => h.Year)
            .Distinct()
            .ToListAsync();

        var availableYears = dbYears
            .Union(new[] { currentYear, currentYear + 1 })
            .OrderBy(y => y)
            .ToList();

        var vm = new HolidayIndexViewModel
        {
            SelectedYear = selectedYear,
            Holidays = holidays,
            AvailableYears = availableYears
        };

        return View(vm);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Generate(int year)
    {
        var holidays = await _holidayService.GenerateHolidaysForYearAsync(year);
        TempData["Success"] = $"Generated {holidays.Count} holidays for {year}.";
        return RedirectToAction(nameof(Index), new { year });
    }

    [HttpGet]
    public IActionResult Create(int? year)
    {
        var vm = new HolidayEditViewModel();
        if (year.HasValue)
            vm.Date = new DateOnly(year.Value, 1, 1);
        return View(vm);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(HolidayEditViewModel model)
    {
        if (!ModelState.IsValid) return View(model);

        var holiday = new Holiday
        {
            Date = model.Date,
            Name = model.Name,
            Year = model.Date.Year,
            IsAutoGenerated = false
        };

        _db.Holidays.Add(holiday);
        await _db.SaveChangesAsync();

        TempData["Success"] = $"Holiday \"{model.Name}\" added.";
        return RedirectToAction(nameof(Index), new { year = holiday.Year });
    }

    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        var holiday = await _db.Holidays.FindAsync(id);
        if (holiday is null) return NotFound();

        var vm = new HolidayEditViewModel
        {
            Id = holiday.Id,
            Date = holiday.Date,
            Name = holiday.Name
        };

        return View(vm);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(HolidayEditViewModel model)
    {
        if (!ModelState.IsValid) return View(model);

        var holiday = await _db.Holidays.FindAsync(model.Id);
        if (holiday is null) return NotFound();

        holiday.Date = model.Date;
        holiday.Name = model.Name;
        holiday.Year = model.Date.Year;

        await _db.SaveChangesAsync();

        TempData["Success"] = $"Holiday \"{model.Name}\" updated.";
        return RedirectToAction(nameof(Index), new { year = holiday.Year });
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        var holiday = await _db.Holidays.FindAsync(id);
        if (holiday is null) return NotFound();

        var year = holiday.Year;
        _db.Holidays.Remove(holiday);
        await _db.SaveChangesAsync();

        TempData["Success"] = $"Holiday \"{holiday.Name}\" deleted.";
        return RedirectToAction(nameof(Index), new { year });
    }
}
